[project]
authors = ["Emanuele Giacomini <giacomini@diag.uniroma1.it>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "rp_nav_suite"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-ament-cmake-auto = ">=1.3.7,<2"
compilers = ">=1.8.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=3.28.3,<4"
ninja = ">=1.12.1,<2"
eigen = ">=3.4.0,<4"
ros-humble-nav2-map-server = ">=1.1.13,<2"
ros-humble-ament-package = ">=0.14.0,<0.15"
opencv = ">=4.9.0,<5"

[activation]
scripts = ["install/setup.sh"]